export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  spaces: '/spaces',
  newSpace: '/spaces/new',
  newSpacePrediction: '/spaces/new/prediction',
  spaceDetail: (spaceId: number | string) => `/spaces/${spaceId}`,
  contracts: '/contracts',
  market: '/market',
  productDetail: (productId: number | string) => `/market/${productId}`,
  myPage: '/mypage',
  myPageProfile: '/mypage/profile',
  myPageWithdraw: '/mypage/withdraw',
} as const;
